import { Payment } from "./Types";

export const data: Payment[] = [
  {
    ID: "1",
    Name: "Payment 1",
    Status: "Running",
    Usage: "5.5",
    Ver: "1.0",
    Age: "1",
  },
  {
    ID: "2",
    Name: "Payment 2",
    Status: "Pending",
    Usage: "10.5",
    Ver: "1.0",
    Age: "2",
  },
  {
    ID: "3",
    Name: "Payment 3",
    Status: "Succeeded",
    Usage: "15.5",
    Ver: "1.0",
    Age: "3",
  },
  {
    ID: "4",
    Name: "Payment 4",
    Status: "Unknown",
    Usage: "20.5",
    Ver: "1.0",
    Age: "4",
  },
  {
    ID: "5",
    Name: "Payment 5",
    Status: "Failed",
    Usage: "25.5",
    Ver: "1.0",
    Age: "5",
  },
  {
    ID: "6",
    Name: "Payment 6",
    Status: "Running",
    Usage: "30.5",
    Ver: "1.0",
    Age: "6",
  },
  {
    ID: "7",
    Name: "Payment 7",
    Status: "Pending",
    Usage: "35.5",
    Ver: "1.0",
    Age: "7",
  },
  {
    ID: "8",
    Name: "Payment 8",
    Status: "Succeeded",
    Usage: "40.5",
    Ver: "1.0",
    Age: "8",
  },
  {
    ID: "9",
    Name: "Payment 9",
    Status: "Unknown",
    Usage: "45.5",
    Ver: "1.0",
    Age: "9",
  },
  {
    ID: "10",
    Name: "Payment 10",
    Status: "Failed",
    Usage: "50.5",
    Ver: "1.0",
    Age: "10",
  },
  {
    ID: "11",
    Name: "Payment 11",
    Status: "Running",
    Usage: "55.5",
    Ver: "1.0",
    Age: "11",
  },
];
